CAMERA_X: 20
CAMERA_Z: 5
cruise_spd: 130
d_nz_ele: 0.0
i_nz_ele: 0.03
i_pitch: 2.0
lim_ele_int: 0.3
min_spd: 80
p_dir_nz: 0.25
p_nz_ele: 0.01
p_pitch: 4.0
p_pitchrate: 0.4
p_roll: 3.0
p_rollrate: 1.0
p_yaw: 1.0
p_yawrate: 0.2

