CAMERA_X: 30
CAMERA_Z: 5
cruise_spd: 300
d_nz_ele: 0.0
gun_pitch: 0.0
i_aoa: 0.1
i_nz_ele: 0.1
i_pitch: 0.1
i_pitchrate: 0.3
i_roll: 0.1
i_rollrate: 0.1
lim_ail_int: 0.5
lim_ele_int: 0.3
max_aoa: 20
max_gcmd: 30
max_pitch_rate: 3
max_roll_rate: 6
min_aoa: -10
min_spd: 100
p_aoa: 1.0
p_dir_nz: 0.02
p_nz_ele: 0.02
p_pitch: 0.5
p_pitchrate: 8.0
p_roll: 1.0
p_rollrate: 6.0
p_yaw: 8.0
p_yawrate: 4.0

