CAMERA_X: 30
CAMERA_Z: 5
cruise_spd: 300
d_nz_ele: 0.0
i_nz_ele: 0.05
i_pitch: 0.5
min_spd: 100
p_dir_nz: 0.3
p_nz_ele: 0.1
p_pitch: 1.5
p_pitchrate: 2.0
p_roll: 4.0
p_rollrate: 1.5
i_rollrate: 0.5
p_yaw: 1.0
p_yawrate: 1.0
p_aoa: 6.0
i_aoa: 2.0
lim_ele_int: 0.6
min_aoa: -10
max_aoa: 15
lim_ail_int: 0.5
max_gcmd: 60