CAMERA_X: 20
CAMERA_Z: 5
cruise_spd: 130
d_nz_ele: 0.0
i_nz_ele: 0.03
i_pitch: 1.0
lim_ele_int: 0.3
min_spd: 80
p_dir_nz: 0.3
p_nz_ele: 0.0
p_pitch: 2.0
p_pitchrate: 2.0
i_pitchrate: 0.0
p_roll: 3.0
p_rollrate: 3.0
p_yaw: 2.0
p_yawrate: 1.0
gun_pitch: 0.0
p_rollrate: 1.0
i_rollrate: 0.5
p_aoa: 3.0
i_aoa: 0.5
min_aoa: -10
max_aoa: 10