# -*- coding: utf-8 -*-
"""
Created on Wed Dec  8 02:42:34 2021

@author: Takumi
"""

OrderedDict([('blues', OrderedDict([('blue_0', OrderedDict([('detect', 1),
                                                            ('distances', array([0.07, 0.  , 0.11, 0.11], dtype=float32)),
                                                            ('fire', 0),
                                                            ('hitpoint', array([1.], dtype=float32)),
                                                            ('inrange', 1),
                                                            ('mrm_num', 2),
                                                            ('tgt_gam_x', array([0.09], dtype=float32)),
                                                            ('tgt_gam_y', array([-1.], dtype=float32)),
                                                            ('tgt_id', 0),
                                                            ('tgt_psi_x', array([0.16], dtype=float32)),
                                                            ('tgt_psi_y', array([-0.99], dtype=float32)),
                                                            ('vector_gam_x', array([-0.76], dtype=float32)),
                                                            ('vector_gam_y', array([0.44], dtype=float32)),
                                                            ('vector_psi_x', array([-1.1], dtype=float32)),
                                                            ('vector_psi_y', array([1.3], dtype=float32)),
                                                            ('velocity', array([0.76], dtype=float32))])),
                                    ('self', OrderedDict([('detect', 1),
                                                          ('distances', array([0.  , 0.07, 0.12, 0.14], dtype=float32)),
                                                          ('fire', 0),
                                                          ('hitpoint', array([1.], dtype=float32)),
                                                          ('inrange', 1),
                                                          ('mrm_num', 2),
                                                          ('tgt_gam_x', array([1.], dtype=float32)),
                                                          ('tgt_gam_y', array([-0.03], dtype=float32)),
                                                          ('tgt_id', 1),
                                                          ('tgt_psi_x', array([0.88], dtype=float32)),
                                                          ('tgt_psi_y', array([-0.48], dtype=float32)),
                                                          ('vector_gam_x', array([0.7], dtype=float32)),
                                                          ('vector_gam_y', array([-0.21], dtype=float32)),
                                                          ('vector_psi_x', array([0.53], dtype=float32)),
                                                          ('vector_psi_y', array([-0.36], dtype=float32)),
                                                          ('velocity', array([-1.19], dtype=float32))]))])),
             ('reds', OrderedDict([('red_0', OrderedDict([('detect', 1),
                                                          ('distances', array([0.12, 0.11, 0.  , 0.02], dtype=float32)),
                                                          ('hitpoint', array([1.], dtype=float32)),
                                                          ('inrange', 1),
                                                          ('mrm_num', 2),
                                                          ('tgt_gam_x', array([1.], dtype=float32)),
                                                          ('tgt_gam_y', array([0.02], dtype=float32)),
                                                          ('tgt_psi_x', array([0.95], dtype=float32)),
                                                          ('tgt_psi_y', array([0.31], dtype=float32))])),
                                   ('red_1', OrderedDict([('detect', 1),
                                                          ('distances', array([0.14, 0.11, 0.02, 0.  ], dtype=float32)),
                                                          ('hitpoint', array([1.], dtype=float32)),
                                                          ('inrange', 1),
                                                          ('mrm_num', 2),
                                                          ('tgt_gam_x', array([1.], dtype=float32)),
                                                          ('tgt_gam_y', array([0.01], dtype=float32)),
                                                          ('tgt_psi_x', array([1.], dtype=float32)),
                                                          ('tgt_psi_y', array([-0.07], dtype=float32))]))]))])
 None, Dict(blues:Dict(blue_0:Dict(detect:Discrete(2),
                                   distances:Box(0.0, 1.0, (4,), float32),
                                   fire:Discrete(2),
                                   hitpoint:Box(0.0, 1.0, (1,), float32),
                                   inrange:Discrete(2),
                                   mrm_num:Discrete(4),
                                   tgt_gam_x:Box(-1.0, 1.0, (1,), float32),
                                   tgt_gam_y:Box(-1.0, 1.0, (1,), float32),
                                   tgt_id:Discrete(2),
                                   tgt_psi_x:Box(-1.0, 1.0, (1,), float32),
                                   tgt_psi_y:Box(-1.0, 1.0, (1,), float32),
                                   vector_gam_x:Box(-1.0, 1.0, (1,), float32),
                                   vector_gam_y:Box(-1.0, 1.0, (1,), float32),
                                   vector_psi_x:Box(-1.0, 1.0, (1,), float32),
                                   vector_psi_y:Box(-1.0, 1.0, (1,), float32),
                                   velocity:Box(-1.0, 1.0, (1,), float32)),
                       self:Dict(detect:Discrete(2),
                                 distances:Box(0.0, 1.0, (4,), float32),
                                 fire:Discrete(2),
                                 hitpoint:Box(0.0, 1.0, (1,), float32),
                                 inrange:Discrete(2),
                                 mrm_num:Discrete(4),
                                 tgt_gam_x:Box(-1.0, 1.0, (1,), float32),
                                 tgt_gam_y:Box(-1.0, 1.0, (1,), float32),
                                 tgt_id:Discrete(2),
                                 tgt_psi_x:Box(-1.0, 1.0, (1,), float32),
                                 tgt_psi_y:Box(-1.0, 1.0, (1,), float32),
                                 vector_gam_x:Box(-1.0, 1.0, (1,), float32),
                                 vector_gam_y:Box(-1.0, 1.0, (1,), float32),
                                 vector_psi_x:Box(-1.0, 1.0, (1,), float32),
                                 vector_psi_y:Box(-1.0, 1.0, (1,), float32),
                                 velocity:Box(-1.0, 1.0, (1,), float32))),
            reds:Dict(red_0:Dict(detect:Discrete(2),
                                 distances:Box(0.0, 1.0, (4,), float32),
                                 hitpoint:Box(0.0, 1.0, (1,), float32),
                                 inrange:Discrete(2),
                                 mrm_num:Discrete(4),
                                 tgt_gam_x:Box(-1.0, 1.0, (1,), float32),
                                 tgt_gam_y:Box(-1.0, 1.0, (1,), float32),
                                 tgt_psi_x:Box(-1.0, 1.0, (1,), float32),
                                 tgt_psi_y:Box(-1.0, 1.0, (1,), float32)),
                      red_1:Dict(detect:Discrete(2),
                                 distances:Box(0.0, 1.0, (4,), float32),
                                 hitpoint:Box(0.0, 1.0, (1,), float32),
                                 inrange:Discrete(2),
                                 mrm_num:Discrete(4),
                                 tgt_gam_x:Box(-1.0, 1.0, (1,), float32),
                                 tgt_gam_y:Box(-1.0, 1.0, (1,), float32),
                                 tgt_psi_x:Box(-1.0, 1.0, (1,), float32),
                                 tgt_psi_y:Box(-1.0, 1.0, (1,), float32)))))
